version: '2.1'

volumes:
    pgmaster:
    pgslave1:
networks:
  postgres-network:

services:
    pgmaster:
        image: paunin/postdock-pgsql
        environment:
            PARTNER_NODES: "pgmaster,pgslave1"
            NODE_ID: 1
            NODE_NAME: node1
            CLUSTER_NODE_NETWORK_NAME: pgmaster
            NODE_PRIORITY: 100
            SSH_ENABLE: 1
            #database we want to use for application
            POSTGRES_PASSWORD: monkey_pass
            POSTGRES_USER: monkey_user
            POSTGRES_DB: monkey_db
            CLEAN_OVER_REWIND: 0
            CONFIGS: "listen_addresses:'*',max_replication_slots:5"
            CLUSTER_NAME: pg_cluster
            REPLICATION_DB: replication_db
            REPLICATION_USER: replication_user
            REPLICATION_PASSWORD: replication_pass
        ports:
            - 5432:5432
        volumes:
            - pgmaster:/var/lib/postgresql/data
        networks:
            - postgres-network
    pgslave1:
        image: paunin/postdock-pgsql
        environment:
            PARTNER_NODES: "pgmaster,pgslave1"
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1
            CLEAN_OVER_REWIND: 1
            CONFIGS: "max_replication_slots:10"
        ports:
            - 5441:5432
        volumes:
            - pgslave1:/var/lib/postgresql/data
        networks:
            - postgres-network
    pgpool:
        image: xingjiudong/postdock-pgpool
        environment:
            constraint:node: =debian_docker09
            PCP_USER: pcp_user
            PCP_PASSWORD: pcp_pass
            WAIT_BACKEND_TIMEOUT: 60
            CHECK_USER: monkey_user
            CHECK_PASSWORD: monkey_pass
            CHECK_PGCONNECT_TIMEOUT: 3
            SSH_ENABLE: 1
            DB_USERS: monkey_user:monkey_pass
            BACKENDS: "0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::"
            REQUIRE_MIN_BACKENDS: 1
            CONFIGS: "num_init_children:250,max_pool:4"
        ports:
            - 5430:5432
            - 9898:9898
        networks:
            - postgres-network
        depends_on:
            - "pgmaster"
            - "pgslave1"
